# docker-compose.yml

services:
  app:
    build: .
    container_name: laravel_demo_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/vendor
      - app/node_modules
    networks:
      - pmasql_network

  web:
    image: nginx:alpine
    container_name: laravel_demo_web
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/vendor
      - /app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pmasql_network

  db:
    image: mysql
    container_name: laravel_demo_app_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: laravel_demo_db
      MYSQL_PASSWORD: admin
    networks:
      - pmasql_network

  pma:
    image: phpmyadmin:latest
    container_name: laravel_demo_pma
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - pmasql_network

volumes:
  db-data:

networks:
  pmasql_network:
    driver: bridge